FROM node:22-alpine
WORKDIR /app

# Copia package.json e yarn.lock (não package-lock.json)
COPY package.json yarn.lock ./

# Instala dependências com yarn
RUN yarn install

COPY . .
EXPOSE 5173
CMD ["yarn", "dev", "--host", "0.0.0.0"]
