services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: maxiprod
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/maxiprod.sql:/docker-entrypoint-initdb.d/maxiprod.sql

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: maxiprod_api
    depends_on:
      - postgres
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # CORRIGIDO: Use o nome EXATO do appsettings.json
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=maxiprod;Username=admin;Password=admin123
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: maxiprod_frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
